---
title: "Share Price vs Fair Value"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rfinance)
library(tidyverse)
library(harrypotter)
library(lubridate)

compute_discount_rate <- function(company, risk_free, equity_risk_premium, max_date) {
  bs <<- get_balance_sheet_statement(company) %>%
    filter(date < max_date) %>%
    filter(date == max(date))
  debt_to_equity <- bs %>%
    mutate(debt_to_equity = `Total debt` / `Total shareholders equity`) %>%
    .$debt_to_equity
  discount_rate <- risk_free * (1 + debt_to_equity) + equity_risk_premium
}
compute_fair_price <- function(company, years = 10, discount_rate, risk_free, forced_increment = NULL, max_date) {
  cf <- get_cash_flow_statement(company) %>% filter(date < max_date)
  fcf <- cf$`Free Cash Flow`
  dr <- discount_rate

  inc_model <-
    cf %>%
    select(date, `Free Cash Flow`) %>%
    mutate(inc = `Free Cash Flow` / lag(`Free Cash Flow`) - 1) %>%
    filter(inc < 1) %>%
    na.omit() %>%
    lm(inc ~ rfinance:::date_to_unix(date), .)

  inc <- inc_model %>%
    predict() %>%
    mean()
  if (!is.null(forced_increment)) inc <- forced_increment
  last_fcf <- cf %>%
    filter(date == max(date)) %>%
    .[["Free Cash Flow"]]

  present_terminal_value <-
    cf %>%
    select(date, `Free Cash Flow`) %>%
    bind_rows(
      tibble(
        n = 1:years
      ) %>%
        mutate(date = ymd(max(cf$date) + 365 * as.numeric(n))) %>%
        mutate(`Free Cash Flow` = last_fcf * (1 + inc)^n) %>%
        mutate(discounted_future_fcf = `Free Cash Flow` / ((1 + dr)^as.numeric(n))) %>%
        select(-n)
    )

  present_value_10yrs <- sum(present_terminal_value$discounted_future_fcf, na.rm = TRUE)
  terminal_value <- present_terminal_value %>%
    filter(date == max(date)) %>%
    .[["Free Cash Flow"]]

  present_value_terminal <- terminal_value * (1 + risk_free) / (discount_rate - risk_free) / (1 + discount_rate)^years

  shares_outstanding <- get_income_statement(company) %>%
    filter(date < max_date) %>%
    filter(date == max(date)) %>%
    .[["Weighted Average Shs Out (Dil)"]]



  fair_price <- (present_value_10yrs + present_value_terminal) / shares_outstanding

  present_terminal_value %>%
    mutate(is_future = date > Sys.Date()) %>%
    ggplot(aes(x = date, y = `Free Cash Flow`, colour = is_future)) +
    geom_point(size = 3) +
    scale_colour_hp_d(option = "lunalovegood")
  return(fair_price)
}
```

```{r}
company <- "MSFT"
dr <- compute_discount_rate(company, risk_free = 0.02, equity_risk_premium = 0.05, max_date = '2018-01-01')
compute_fair_price(company, 10, discount_rate = dr, risk_free = 0.02, forced_increment = NULL, max_date = '2018-01-01')
```

```{r}
dates <- seq.Date(from = as.Date('2014-01-01'), to = as.Date('2020-01-01'), by = 'day')

dr <- c()
fp <- c()

for(i in 1:length(dates)){
  dr[[i]] <- compute_discount_rate(company, risk_free = 0.02, equity_risk_premium = 0.05, max_date = dates[[i]])
  fp[[i]] <- compute_fair_price(company, 10, discount_rate = dr[[i]], risk_free = 0.02, forced_increment = NULL, max_date = dates[[i]])
}
```
